title: Site

pages:
  template:
    - list
    - default
    - external


fields:
  title:
    label: Site Title
    type:  text

  description:
    label: Description
    type: textarea
    buttons:

  logo:
    label: Logo
    type: image
    help: Should be in SVG format; used on homepage
    width: 1/2

  logo_alt:
    label: Alternative Logo
    type: image
    help: Should be in SVG format; used on secondary pages
    width: 1/2

  keywords:
    label: Keywords
    type: tags

  home_title:
    label: Homepage title
    type: text
    help: super brief description

  footer_address:
    label: Footer address
    type: textarea
    buttons:

  meta_image:
    label: Meta image
    type: image
    help: This image will be used as a default image when posting a link on social media