title: Site

pages:
  template:
    - list
    - default
    - external


fields:
  title:
    label: Site Title
    type:  text

  description:
    label: Description
    type:  textarea

  logo:
    label: Logo
    type: image
    help: Should be in SVG format

  keywords:
    label: Keywords
    type: tags

  home_title:
    label: Homepage title
    type: text
    help: super brief description

  meta_image:
    label: Meta image
    type: image
    help: This image will be used as a default image when posting a link on social media